### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by 2007lf** [kayako/magento-integration#6]
hi, I met error, I cant find why, I server information 
PHP 5.3.27 
nginx/1.5.6

I had check error.log
[error] 14780#0: *18347746 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Zend_Log' not found in /var/www/test2/lib/KayakoAPI/kyCommentBase.php on line 552" ,
552 is the last line, and that file includes no call to Zend_Log.
somebody can help me? thanks

**Comment by nidhigupta-22** [comment]
Hey Daniel,

As your case was assisted on chat and issue was resolved there, m closing the issue for now. Please feel free to contact us for further concern.

Thanks,
Nidhi
