### ISSUE TITLE
No compatibility with Magento 1.9.3

### ISSUE THREAD

**Issue by markmeijers** [kayako/magento-integration#8]
This extension is not compatible with Magento 1.9.3. It worked fine with 1.9.1, but after Magento's security patches the View Tickets page (/client/index/viewTicket/) no longer works. It is an empty page with only the sidebar. I whitelisted the block (client/viewticket and client/viewTicket).

I tried this in both my current store and in a clean/fresh/new Magento installation as well...

**Comment by markmeijers** [comment]
On a fresh install an exception:
`2017-02-11T11:03:14+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Kayako_Client_Block_ViewTicket' in /home/****/public_html/app/Mage.php:595
Stack trace:
#0 /home/****/public_html/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /home/****/public_html/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('client/viewTick...', Array)
#2 /home/****/public_html/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('client/viewTick...', 'viewTicket')
#3 /home/****/public_html/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('client/viewTick...', 'viewTicket')
#4 /home/****/public_html/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /home/****/public_html/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /home/****/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /home/****/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /home/****/public_html/app/code/community/Kayako/Client/controllers/IndexController.php(208): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /home/****/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Kayako_Client_IndexController->viewTicketAction()
#10 /home/****/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('viewTicket')
#11 /home/****/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /home/****/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#13 /home/****/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /home/****/public_html/index.php(83): Mage::run('', 'store')
#15 {main}
`

**Comment by mansiwason** [comment]
PR for the fix is - https://github.com/kayako/magento-integration/pull/9

One can download the kayako integration with the latest magento module at https://github.com/kayako/magento-integration/
